# Generated by Django 4.2.10 on 2025-05-27 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_message_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
